### ISSUE TITLE
Model City is missing crucial field

### ISSUE THREAD

**Issue by tkachenkoas** [xSAVIKx/openweathermap-java-api#10]
Model org.openweathermap.api.model.forecast.City is missing a crucial field 'timezone' returned from api openweathermap.

Since api returns date and time in UTC timezone, you'll have to make some workaround in order to get localdatetime from coordinates (and use external api or external dependencies)...

**Comment by xSAVIKx** [comment]
@tkachenkoas I have updated the `City` model. Now it has the `timezone` field. It is not released to maven repos yet, but you can compile it on your own.

I don't fully get what you meant in the second sentence, but you're free to reach me if you need some help.

**Comment by tkachenkoas** [comment]
Thank you for such a quick patch! Already using development-snapshot version with timezone.

In second sentence I meant that you lib's client will have to make some additional calculations using coordinates to get timezone as a workaround. I also had a crazy idea of using ASM to add the field at classload time =)
