### ISSUE TITLE
ISOStringDateTypeAdapter sets wrong timezone and uses SimpleDateFormat

### ISSUE THREAD

**Issue by tkachenkoas** [xSAVIKx/openweathermap-java-api#12]
Openweather API states that they return date-time of calculation in UTC timezone
https://openweathermap.org/api/hourly-forecast#JSON
>>> list.dt_txt Data/time of calculation, UTC

However, when deserialization takes place, ISOStringDateTypeAdapter is using rough 'new SimpleDateFormat(ISO_DATE_FORMAT)' without timezone which results in system default timezone.
Also, I don't think that using SimpleDateFormat is a good solution for parallel operation. I suggest using FastDateFormat of ThreadLocal for SDF if you don't want additional dependencies for you lib.

**Comment by xSAVIKx** [comment]
@tkachenkoas tnx for the issue. I have plans for the v.2 to migrate to Java8 time API, but it'll break the compatibility. As for now, you're right, it's better to use a thread-local SDF instance.

**Comment by tkachenkoas** [comment]
Okay, then meanwhile I'll make manual transitions between timezones.

Even though SDF is not thread-safe, I'm not sure that Gson caches the adapter instance. at least documentation says nothing about it =)
