### ISSUE TITLE
Failed to read artifact descriptor for org.openweathermap.java-api:api-core:jar:1.2.3

### ISSUE THREAD

**Issue by kendyjm** [xSAVIKx/openweathermap-java-api#22]
Hi !
the following error appeared on my project some days ago: 

`Could not resolve dependencies for project com.xxx.yyy:jar:0.1-SNAPSHOT: Failed to collect dependencies at org.openweathermap.java-api:api-core:jar:1.2.3: Failed to read artifact descriptor for org.openweathermap.java-api:api-core:jar:1.2.3: Could not transfer artifact org.openweathermap.java-api:api-core:pom:1.2.3 from/to bintray-xsavikx-openweathermap-java-api (https://dl.bintray.com/xsavikx/openweathermap-java-api)`

to confirm, when I try to manually download the jar https://jcenter.bintray.com/org/openweathermap/java-api/api-core/1.2.3/api-core-1.2.3.jar at https://mvnrepository.com/artifact/org.openweathermap.java-api/api-core/1.2.3 it fails with error 403.

could you fix this issue please ?

best regards,
kendy

**Comment by xSAVIKx** [comment]
Hey @kendyjm. Thx for reaching out. 

Bintray is dead for over a year already, so there's no way to fix this from the Bintray perspective. The project is now available through GitHub packages. 

You can check the GH packages docs here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#installing-a-package

And the packages themselves and related versions are available here: https://github.com/xSAVIKx/openweathermap-java-api/packages/857730/versions

**Comment by kendyjm** [comment]
thank you for this quick reply!
it seems that my current version (1.2.3) is not available as a package on github: should I move to the 1.4.0 version ? are there breaking changes between 1.2.3 ànd 1.4.0 ? where can I found the release notes ?

thanks!

**Comment by xSAVIKx** [comment]
Yeah, older versions were not backported but everything is backward-compatible. The latest releases were only dependency upgrades and CI/cleanup features. You should be safe to migrate to the latest one.

**Comment by kendyjm** [comment]
thank you for these informations!
