### ISSUE TITLE
cannot build 

### ISSUE THREAD

**Issue by mihneaocian** [xSAVIKx/openweathermap-java-api#5]
i'm trying to get the jars to get in my project and when i'm running the graddle script for building i'm getting:
11:37:02 AM: Executing task...

Could not determine java version from '11.0.2'.
11:37:04 AM: Task execution finished.

**Comment by xSAVIKx** [comment]
@mihneaocian yeah, it's not possible to build the project with JDK 11 yet, cause the bundled Gradle version (v4.4.1) just cannot run with it.
You can try to switch your default JDK version to JDK 8 or wait for some time until I'll upgrade the build configuration.
